# Generated by Django 3.2.3 on 2021-06-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_store', '0002_remove_issuebook_fine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebook',
            name='return_date',
            field=models.DateTimeField(blank=True, default='2000-01-01', null=True),
        ),
    ]
