# Generated by Django 3.2.3 on 2021-06-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_store', '0003_alter_issuebook_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuebook',
            name='return_date',
            field=models.DateTimeField(default='2000-1-1'),
        ),
    ]
